// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAuM_6kOd713wp5ysmtiTs6FHlTHFYATc',
    appId: '1:534232131874:web:2aa85c56da25b74e489d7b',
    messagingSenderId: '534232131874',
    projectId: 'scoopify-dbe3a',
    authDomain: 'scoopify-dbe3a.firebaseapp.com',
    storageBucket: 'scoopify-dbe3a.firebasestorage.app',
    measurementId: 'G-9EVWRXR0NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAwdRvMI-fNO387AghIVBMePPRkA--8D0',
    appId: '1:534232131874:android:9f7e3df4272f1c78489d7b',
    messagingSenderId: '534232131874',
    projectId: 'scoopify-dbe3a',
    storageBucket: 'scoopify-dbe3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnrFl_oUTuiySP1D01V1plhC6Gq7to7mI',
    appId: '1:534232131874:ios:a2717c01ab63377f489d7b',
    messagingSenderId: '534232131874',
    projectId: 'scoopify-dbe3a',
    storageBucket: 'scoopify-dbe3a.firebasestorage.app',
    iosBundleId: 'com.andreaferrario.scoopify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnrFl_oUTuiySP1D01V1plhC6Gq7to7mI',
    appId: '1:534232131874:ios:a2717c01ab63377f489d7b',
    messagingSenderId: '534232131874',
    projectId: 'scoopify-dbe3a',
    storageBucket: 'scoopify-dbe3a.firebasestorage.app',
    iosBundleId: 'com.andreaferrario.scoopify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAuM_6kOd713wp5ysmtiTs6FHlTHFYATc',
    appId: '1:534232131874:web:bb2cc3ff397b0088489d7b',
    messagingSenderId: '534232131874',
    projectId: 'scoopify-dbe3a',
    authDomain: 'scoopify-dbe3a.firebaseapp.com',
    storageBucket: 'scoopify-dbe3a.firebasestorage.app',
    measurementId: 'G-5L81RT2PC6',
  );
}
